### ISSUE TITLE
Installation requires global bower

### ISSUE THREAD

**Issue by wolfgang42** [idleberg/m8tro-bootstrap#12]
`npm install m8tro-bootstrap` will fail if `bower` has not been installed globally. I have a CI system which builds my program; because of this I have to add `npm install --global bower` as a build step.

Why not just add `bower` as a dependency and use `node_modules/.bin/bower install` instead?

**Comment by wolfy1339** [comment]
`bower` is in devDependencies already, I would suggest using a method like suggested on this [StackOverflow question](http://stackoverflow.com/questions/23076968/npm-postinstall-only-on-development)

**Comment by wolfgang42** [comment]
It's in devDependencies, yes, but I'm not *developing* m8tro-bootstrap, just installing it as a dependency of my project.

I'm not sure how that StackOverflow question is supposed to help; it looks like all the answers would involve me editing m8tro-bootstrap's `package.json` file. Is there something I'm missing?

**Comment by wolfgang42** [comment]
I will look at how some other packages do it and see what I find.

**Comment by wolfy1339** [comment]
You can fork the project, make the required changes and make a pull request

**Comment by idleberg** [comment]
It's indeed silly at this point to still rely on both, node and bower. I think there _was_ the need to use both in the past.
