### ISSUE TITLE
Using wrong NPM package of Font Awesome

### ISSUE THREAD

**Issue by wolfy1339** [idleberg/m8tro-bootstrap#13]
You are using the wrong NPM package for Font Awesome, ref: https://github.com/FortAwesome/Font-Awesome/blob/master/package.json#L2 and this error
```
npm ERR! No compatible version found: fontawesome@^4.6.3
```

**Comment by wolfy1339** [comment]
Fixed by e6b1e66e5a68bdd958f432cb62329b66b8e1106d

**Comment by wolfy1339** [comment]
This is still an issue in Gulpfile.js

**Comment by wolfy1339** [comment]
Seems to be addressed everywhere now.
Fixed by e6b1e66 and 4541a2bc4ae5da42e019a66540e4106c50d3999b

**Comment by idleberg** [comment]
Thanks! I'm looking forward to Bootstrap 4, since I plan to redo this theme from scratch, probably going in a slightly different direction. We'll see!
