### ISSUE TITLE
Demo only shows the primary button having an effect

### ISSUE THREAD

**Issue by IngwiePhoenix** [idleberg/m8tro-bootstrap#3]
I just looked at the demo and got a little confused, that only the primary button type had the color transistion effect. Is that only on the demo or also on the actual code?

**Comment by idleberg** [comment]
the primary has different `:hover` properties than the rest of the buttons, it's the only state that changes the `background-color` of the button. all other buttons indicate hover-state by changing their `border-color`.

**Comment by IngwiePhoenix** [comment]
Ahh so it’s on purpose. Okay then! :) I thought it was a bug, since the hover effect on the border is hardly visible.
