### ISSUE TITLE
Upgrade to Bootstrap v4

### ISSUE THREAD

**Issue by wolfy1339** [idleberg/m8tro-bootstrap#4]
It would be cool to start making a new version that is based on Bootstrap 4.0.0 since it's in Alpha stage right now, so your release of m8tro-bootstrap can be released as soon as it is released.

**Comment by idleberg** [comment]
Just stop requesting updates each and every time there's a change

**Comment by wolfy1339** [comment]
>Thanks! I'm looking forward to Bootstrap 4, since I plan to redo this theme from scratch, probably going in a slightly different direction. We'll see!
I have a suggestion: Is it possible to turn this into a fork of bootstrap and use their source files, and add our styles to them so we aren't duplicating classes?

**Comment by idleberg** [comment]
As I've said elsewhere, v4 will be very different from v3, since my interests have shifted. I will recreate it from scratch, with some huge differences.

> Is it possible to turn this into a fork of bootstrap and use their source files, and add our styles to them so we aren't duplicating classes?

Classes are overwritten, not duplicated. Also, as of the current Bootstrap 4 alpha, customization has become even easier.
